export type Priority = 'Critical' | 'High' | 'Medium' | 'Informational';
export type NoticeStatus = 'Active' | 'Draft' | 'Pending Approval' | 'Expired';
export type NoticeType =
  | 'Safety Flash' |'Operational Instructions' |'Airside Notice' |'Ground Handling Procedures' |'Security Directive' |'Flight Operations Update' |'Emergency Notification' |'Service Bulletin' |'Airline Memo' |'Regulatory Update';

export type NoticeCategory = 'Safety Flash' | 'Operational Memo' | 'Urgent Notice' | 'General Information';

export interface Notice {
  id: string;
  refNumber: string;
  title: string;
  type: NoticeType;
  category: NoticeCategory;
  priority: Priority;
  status: NoticeStatus;
  publishedBy: string;
  publishedDate: string;
  effectiveDate: string;
  expiryDate: string;
  targetAirlines: string[];
  ackPercentage: number;
  totalRecipients: number;
  acknowledged: number;
  escalated: boolean;
  escalationLevel: 0 | 1 | 2 | 3;
  requiresSignature: boolean;
}

export const airlines = [
  'EgyptAir',
  'Air Arabia',
  'flydubai',
  'Qatar Airways',
  'Emirates',
  'Turkish Airlines',
  'Lufthansa',
  'British Airways',
];

export const notices: Notice[] = [
  {
    id: 'notice-001',
    refNumber: 'SF-2026-047',
    title: 'Airside Vehicle Incident — Taxiway Echo Closure Immediate Safety Flash',
    type: 'Safety Flash',
    category: 'Safety Flash',
    priority: 'Critical',
    status: 'Active',
    publishedBy: 'Karim Abdallah',
    publishedDate: '09/09/2026 08:14',
    effectiveDate: '09/09/2026 08:14',
    expiryDate: '10/09/2026 08:14',
    targetAirlines: ['EgyptAir', 'Air Arabia', 'flydubai', 'Qatar Airways', 'Emirates', 'Turkish Airlines', 'Lufthansa', 'British Airways'],
    ackPercentage: 62,
    totalRecipients: 24,
    acknowledged: 15,
    escalated: true,
    escalationLevel: 2,
    requiresSignature: true,
  },
  {
    id: 'notice-002',
    refNumber: 'OI-2026-031',
    title: 'Revised Boarding Procedure — Gates B12 to B18 Effective Immediately',
    type: 'Operational Instructions',
    category: 'Operational Memo',
    priority: 'High',
    status: 'Active',
    publishedBy: 'Nadia Samir',
    publishedDate: '08/09/2026 14:30',
    effectiveDate: '09/09/2026 06:00',
    expiryDate: '30/09/2026 23:59',
    targetAirlines: ['EgyptAir', 'Qatar Airways', 'Emirates', 'British Airways'],
    ackPercentage: 75,
    totalRecipients: 16,
    acknowledged: 12,
    escalated: true,
    escalationLevel: 1,
    requiresSignature: false,
  },
  {
    id: 'notice-003',
    refNumber: 'SD-2026-022',
    title: 'Enhanced Security Screening Protocol — Terminal 2 International Departures',
    type: 'Security Directive',
    category: 'Urgent Notice',
    priority: 'Critical',
    status: 'Active',
    publishedBy: 'Ahmed Hosny',
    publishedDate: '07/09/2026 11:00',
    effectiveDate: '07/09/2026 12:00',
    expiryDate: '21/09/2026 12:00',
    targetAirlines: ['EgyptAir', 'Air Arabia', 'flydubai', 'Qatar Airways', 'Emirates', 'Turkish Airlines', 'Lufthansa', 'British Airways'],
    ackPercentage: 88,
    totalRecipients: 32,
    acknowledged: 28,
    escalated: false,
    escalationLevel: 0,
    requiresSignature: true,
  },
  {
    id: 'notice-004',
    refNumber: 'GHP-2026-019',
    title: 'Updated Baggage Handling Procedures — Oversized Baggage Ramp Area 4',
    type: 'Ground Handling Procedures',
    category: 'Operational Memo',
    priority: 'Medium',
    status: 'Active',
    publishedBy: 'Karim Abdallah',
    publishedDate: '06/09/2026 09:45',
    effectiveDate: '08/09/2026 00:00',
    expiryDate: '06/12/2026 00:00',
    targetAirlines: ['EgyptAir', 'Air Arabia', 'flydubai', 'Emirates'],
    ackPercentage: 100,
    totalRecipients: 12,
    acknowledged: 12,
    escalated: false,
    escalationLevel: 0,
    requiresSignature: false,
  },
  {
    id: 'notice-005',
    refNumber: 'FOU-2026-015',
    title: 'Flight Operations Update — RNAV Approach Procedure Changes Cairo RWY 05C',
    type: 'Flight Operations Update',
    category: 'Urgent Notice',
    priority: 'High',
    status: 'Active',
    publishedBy: 'Nadia Samir',
    publishedDate: '05/09/2026 16:20',
    effectiveDate: '06/09/2026 00:01',
    expiryDate: '05/10/2026 00:01',
    targetAirlines: ['EgyptAir', 'Qatar Airways', 'Emirates', 'Lufthansa', 'British Airways'],
    ackPercentage: 93,
    totalRecipients: 20,
    acknowledged: 18,
    escalated: false,
    escalationLevel: 0,
    requiresSignature: true,
  },
  {
    id: 'notice-006',
    refNumber: 'AN-2026-033',
    title: 'FOD Sweep Alert — Apron Delta Sector — Mandatory Vehicle Halt Protocol',
    type: 'Airside Notice',
    category: 'Safety Flash',
    priority: 'Critical',
    status: 'Active',
    publishedBy: 'Tamer Farouk',
    publishedDate: '09/09/2026 06:50',
    effectiveDate: '09/09/2026 07:00',
    expiryDate: '09/09/2026 18:00',
    targetAirlines: ['EgyptAir', 'Air Arabia', 'flydubai', 'Qatar Airways', 'Emirates', 'Turkish Airlines'],
    ackPercentage: 50,
    totalRecipients: 18,
    acknowledged: 9,
    escalated: true,
    escalationLevel: 1,
    requiresSignature: false,
  },
  {
    id: 'notice-007',
    refNumber: 'RU-2026-011',
    title: 'ECAA Regulatory Update — Ground Staff Certification Renewal Requirements 2027',
    type: 'Regulatory Update',
    category: 'General Information',
    priority: 'Informational',
    status: 'Active',
    publishedBy: 'Ahmed Hosny',
    publishedDate: '03/09/2026 10:00',
    effectiveDate: '01/01/2027 00:00',
    expiryDate: '31/12/2027 00:00',
    targetAirlines: ['EgyptAir', 'Air Arabia', 'flydubai', 'Qatar Airways', 'Emirates', 'Turkish Airlines', 'Lufthansa', 'British Airways'],
    ackPercentage: 72,
    totalRecipients: 24,
    acknowledged: 17,
    escalated: false,
    escalationLevel: 0,
    requiresSignature: false,
  },
  {
    id: 'notice-008',
    refNumber: 'EN-2026-008',
    title: 'Emergency Notification — Khamsin Weather Disruption Ground Operations Suspended',
    type: 'Emergency Notification',
    category: 'Urgent Notice',
    priority: 'Critical',
    status: 'Expired',
    publishedBy: 'Karim Abdallah',
    publishedDate: '01/09/2026 03:30',
    effectiveDate: '01/09/2026 04:00',
    expiryDate: '01/09/2026 20:00',
    targetAirlines: ['EgyptAir', 'Air Arabia', 'flydubai', 'Qatar Airways', 'Emirates', 'Turkish Airlines', 'Lufthansa', 'British Airways'],
    ackPercentage: 96,
    totalRecipients: 32,
    acknowledged: 31,
    escalated: false,
    escalationLevel: 0,
    requiresSignature: true,
  },
  {
    id: 'notice-009',
    refNumber: 'SB-2026-005',
    title: 'Service Bulletin — Ground Power Unit Fleet Maintenance Downtime Schedule',
    type: 'Service Bulletin',
    category: 'General Information',
    priority: 'Medium',
    status: 'Active',
    publishedBy: 'Tamer Farouk',
    publishedDate: '02/09/2026 08:00',
    effectiveDate: '04/09/2026 00:00',
    expiryDate: '04/10/2026 00:00',
    targetAirlines: ['EgyptAir', 'Air Arabia', 'Emirates', 'Turkish Airlines'],
    ackPercentage: 85,
    totalRecipients: 14,
    acknowledged: 12,
    escalated: false,
    escalationLevel: 0,
    requiresSignature: false,
  },
  {
    id: 'notice-010',
    refNumber: 'AM-2026-027',
    title: 'Airline Memo — Gate Allocation Changes T2 — EgyptAir Domestic Operations',
    type: 'Airline Memo',
    category: 'Operational Memo',
    priority: 'Medium',
    status: 'Active',
    publishedBy: 'Nadia Samir',
    publishedDate: '04/09/2026 12:15',
    effectiveDate: '05/09/2026 00:00',
    expiryDate: '19/09/2026 23:59',
    targetAirlines: ['EgyptAir'],
    ackPercentage: 100,
    totalRecipients: 6,
    acknowledged: 6,
    escalated: false,
    escalationLevel: 0,
    requiresSignature: false,
  },
  {
    id: 'notice-011',
    refNumber: 'OI-2026-029',
    title: 'Revised De-icing Procedures — Onset of Winter Operations Season',
    type: 'Operational Instructions',
    category: 'Operational Memo',
    priority: 'High',
    status: 'Draft',
    publishedBy: 'Ahmed Hosny',
    publishedDate: '—',
    effectiveDate: '01/11/2026 00:00',
    expiryDate: '31/03/2027 00:00',
    targetAirlines: ['EgyptAir', 'Lufthansa', 'British Airways', 'Turkish Airlines'],
    ackPercentage: 0,
    totalRecipients: 16,
    acknowledged: 0,
    escalated: false,
    escalationLevel: 0,
    requiresSignature: false,
  },
  {
    id: 'notice-012',
    refNumber: 'SD-2026-024',
    title: 'Security Directive — Unattended Baggage Protocol Update per ICAO Annex 17',
    type: 'Security Directive',
    category: 'Urgent Notice',
    priority: 'High',
    status: 'Pending Approval',
    publishedBy: 'Karim Abdallah',
    publishedDate: '—',
    effectiveDate: '12/09/2026 00:00',
    expiryDate: '12/12/2026 00:00',
    targetAirlines: ['EgyptAir', 'Air Arabia', 'flydubai', 'Qatar Airways', 'Emirates', 'Turkish Airlines', 'Lufthansa', 'British Airways'],
    ackPercentage: 0,
    totalRecipients: 32,
    acknowledged: 0,
    escalated: false,
    escalationLevel: 0,
    requiresSignature: true,
  },
  {
    id: 'notice-013',
    refNumber: 'GHP-2026-020',
    title: 'Cargo Handling Procedure Update — Dangerous Goods Class 1 Segregation',
    type: 'Ground Handling Procedures',
    category: 'Operational Memo',
    priority: 'High',
    status: 'Active',
    publishedBy: 'Tamer Farouk',
    publishedDate: '07/09/2026 13:00',
    effectiveDate: '08/09/2026 00:00',
    expiryDate: '07/12/2026 00:00',
    targetAirlines: ['EgyptAir', 'Qatar Airways', 'Emirates', 'Lufthansa', 'British Airways'],
    ackPercentage: 68,
    totalRecipients: 18,
    acknowledged: 12,
    escalated: false,
    escalationLevel: 0,
    requiresSignature: false,
  },
  {
    id: 'notice-014',
    refNumber: 'RU-2026-012',
    title: 'GCAA Alignment Update — Ground Handling License Reciprocity Agreement',
    type: 'Regulatory Update',
    category: 'General Information',
    priority: 'Informational',
    status: 'Active',
    publishedBy: 'Ahmed Hosny',
    publishedDate: '01/09/2026 09:00',
    effectiveDate: '01/09/2026 09:00',
    expiryDate: '01/03/2027 00:00',
    targetAirlines: ['Air Arabia', 'flydubai', 'Qatar Airways', 'Emirates'],
    ackPercentage: 90,
    totalRecipients: 12,
    acknowledged: 11,
    escalated: false,
    escalationLevel: 0,
    requiresSignature: false,
  },
  {
    id: 'notice-015',
    refNumber: 'AN-2026-034',
    title: 'Apron Speed Limit Enforcement — Increased Monitoring Zone November Bravo',
    type: 'Airside Notice',
    category: 'Safety Flash',
    priority: 'Medium',
    status: 'Active',
    publishedBy: 'Nadia Samir',
    publishedDate: '08/09/2026 10:30',
    effectiveDate: '08/09/2026 12:00',
    expiryDate: '22/09/2026 12:00',
    targetAirlines: ['EgyptAir', 'Air Arabia', 'flydubai', 'Qatar Airways', 'Emirates', 'Turkish Airlines'],
    ackPercentage: 55,
    totalRecipients: 18,
    acknowledged: 10,
    escalated: false,
    escalationLevel: 0,
    requiresSignature: false,
  },
];